### ISSUE TITLE
https access

### ISSUE THREAD

**Issue by DiouxX** [DiouxX/docker-glpi#1]
Enable ssl module on apache to access GLPI on HTTPS. For example with Let's Encrypt.

**Comment by Lunaden** [comment]
Maybe it's better to let another service do that like : https://github.com/jwilder/nginx-proxy
or traefik if you use swarm

**Comment by DiouxX** [comment]
Yes i'm working on with my another repository : https://github.com/DiouxX/docker-apache-proxy

i've need more times for this issue ;)

**Comment by DiouxX** [comment]
Finally for HTTPS Support, i redirect to :

- Proxy: https://github.com/jwilder/nginx-proxy
- HTTPS Let's Encrypt : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
