### ISSUE TITLE
Discussion : apt-get upgrade

### ISSUE THREAD

**Issue by Lunaden** [DiouxX/docker-glpi#10]
Make a forced apt-get upgrade in you start script is not a good idea.
You will have weird beahaviour with this and container start will be really slow.
+ You already use debian:latest in your DockerFile

d8ff9bd5e09635723b2076eff8d9a41ebc52859c

**Comment by DiouxX** [comment]
apt upgrade is on Dockerfile not in `glpi-start.sh`

So this upgrade run only that i construct docker image not on start container.

I hesitated to add upgrade beacuse i use debian:latest but i don't know the best practice about this

**Comment by Lunaden** [comment]
My bad... Not sure if it is useful. I'm going to make some search for this...
