### ISSUE TITLE
PHP directive "session.cookie_httponly" and timezone on Asustor NAS

### ISSUE THREAD

**Issue by lmateovf** [DiouxX/docker-glpi#101]
Hello!
First of all, thank you for making this project. It's very nice...

I need help with this warning in the installation process with the PHP directive "session.cookie_httponly":

<img width="1247" alt="imagen" src="https://github.com/DiouxX/docker-glpi/assets/62722086/04009270-0c41-4798-a5af-36936fc99535">
I don't know if there is a specific env variable or command which I can use to set up that GLPI security warning...

-------------------------------------------------
also, in the readme, you mention two volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      
Do you know where are those files on an Asustor NAS (with the stock OS: ADM)... It's were i have my Portainer and docker.... I also own an Ubuntu server so it's no problem if you don't know, because those files do exist on Ubuntu...

**Comment by DiouxX** [comment]
Hello,

For the PHP directive, I need to check first but I found this topic on the GLPI forum on this subject https://forum.glpi-project.org/viewtopic.php?id=285285
It seems to be in the _php.ini_ file that needs to be modified.

For the **timezone** and **localtime** volumes, I don't know where these files are on the Asustor NAS.
But they 're not mandatory volumes, you can delete the volumes from your docker-compose file without impacting the behavior of the container.

**Comment by lmateovf** [comment]
> Hello,
Hi!
 
> For the PHP directive, I need to check first but I found this topic on the GLPI forum on this subject https://forum.glpi-project.org/viewtopic.php?id=285285 It seems to be in the _php.ini_ file that needs to be modified.

Ok, no problem, I will access the GLPI container through CLI and edit that file, hopefully the change will persist after an update or similar event for example...

> For the **timezone** and **localtime** volumes, I don't know where these files are on the Asustor NAS. But they 're not mandatory volumes, you can delete the volumes from your docker-compose file without impacting the behavior of the container.

Ok, good to know!


Thank you very much for the fast response!
Hope you have a nice day!

**Comment by ftoledo** [comment]
for the session.cookie_httponly you  can add a custom conf like the timezone to the build script... example:

```
echo "session.cookie_httponly = on" > /etc/php/8.1/apache2/conf.d/glpi_settings.ini;
echo "session.cookie_httponly = on" > /etc/php/8.1/cli/conf.d/glpi_settings.ini;
```
also i think that need to upload_max_filesize, post_max_size, memory_limit and 

so  better.. add new include path to php ini .. like /usr/local/custom-php.d/

then you can mount that volumen to persist php configs
php.d:/usr/local/custom.php.d

**Comment by DiouxX** [comment]
PR #105 normally solves this issue

**Comment by lmateovf** [comment]
Thank you very much!
Now I don't have my server available but whenever I can I will test it
