### ISSUE TITLE
Has the docker image diouxx/glpi been updated to GLPI Version 10.0.12 ? 

### ISSUE THREAD

**Issue by wedowhateverwewant** [DiouxX/docker-glpi#107]
Has the docker image diouxx/glpi been updated to GLPI Version 10.0.12 ?

**Comment by DiouxX** [comment]
Hello,

It is not necessary to upgrade GLPI image.
By default, during a new installation, it is the last version of GLPI which is downloaded.
Currently it is the version 10.0.14 (https://github.com/glpi-project/glpi/releases/).

For an existing installation, to update your GLPI, you must update it with the "classic" method as explained in this closed issue #61

**Comment by wedowhateverwewant** [comment]
Hi,

So I did the update the way you mentioned and all is well, but im getting these errors when the docker compose file is running,

mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mariadb  | 2024-03-12 17:15:49 52 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).


Any help is appreciated

**Comment by DiouxX** [comment]
After upgrading to a newer version, you had no process to update the database schema via the web page ?

The problem would be more with glpi than with the Docker image.
It would be interesting to ask this question on the GLPI forum.

**Comment by wedowhateverwewant** [comment]
passing the env variable MARIADB_AUTO_UPGRADE=1 in the mariadb.env seems to do the job, no more errors.
