### ISSUE TITLE
GLPI does not show Images and doesn't attache documents

### ISSUE THREAD

**Issue by robertocpiconi** [DiouxX/docker-glpi#119]
Hi,

GLPI was working fine, but suddenly it stopped showing images and attachment files.
![image](https://github.com/DiouxX/docker-glpi/assets/96170956/5119a4d1-1d61-4b0e-99ea-c183e0230ce2)

![image](https://github.com/DiouxX/docker-glpi/assets/96170956/ade5c6a2-4cb4-4175-a7fc-3d451d3bceec)

![image](https://github.com/DiouxX/docker-glpi/assets/96170956/aa7ca7cc-1e05-4ce7-8964-3e4cc35833e5)

Can you help us?

We already tried to recreate the container and check directory permissions.

Best regards.

**Comment by DiouxX** [comment]
Hello,

Which GLPI version are you using and which docker image ?

**Comment by robertocpiconi** [comment]
Hello,

Thanks for your fast response.

Information:

- GLPI 10.0.3
![image](https://github.com/DiouxX/docker-glpi/assets/96170956/3f3b15e6-5b2b-4b8c-a77e-60faf285a830)

- Docker image: diouxx/glpi

```
diouxx/glpi             latest      sha256:a37c4e5acf37d3981e48a364ea0132c1b0e5ffb0d4bfff47caf30b45e458ddd0   21cf900de1c9
``` 

Error when I try to upload(Copy and Paste) an image.
![image](https://github.com/DiouxX/docker-glpi/assets/96170956/194aab26-e50e-42e3-aaa4-db0b892efdd5)

And there are no errors when I upload an attachment.

Permissions are set to use www-data as owner and group.
![image](https://github.com/DiouxX/docker-glpi/assets/96170956/41b23f5b-f331-4f67-9f12-a3cd0b35d49e)

**Comment by robertocpiconi** [comment]
Hello.

I've founded the solution.

1. Connect into GLPI container
2. Run `php bin/console glpi:database:check_schema_integrity`
3. This command will show you multiple tables that is not correct configured.
4. Fix all table and columns in DB.
5. Check again inside GLPI container if there is table that still needed to be fixed.
6. Run `php bin/console glpi:migration:unsigned_key`

Now you are good to go.
