### ISSUE TITLE
Failing to download GLPI source code

### ISSUE THREAD

**Issue by lucaspottersky** [DiouxX/docker-glpi#15]
`docker run -it --name glpi -p 80:80 diouxx/glpi`

The command above is failing because it's trying to download GLPI from the URL
https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.0.tgz
instead of
https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.tgz

**Comment by bradpoulton** [comment]
I am also having this issue. 
`TIMEZONE is unset
TLS_REQCERT isn't present
--2018-08-24 06:32:26--  https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.0.tgz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-24 06:32:26 ERROR 404: Not Found.

tar (child): /var/www/html/glpi-9.3.0.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Starting periodic command scheduler: cron.
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
Restarting Apache httpd web server: apache2.
Stopping Apache httpd web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message`

**Comment by DiouxX** [comment]
Issue is solved by Pull request #16
