### ISSUE TITLE
Doesn't work with recent version of MySQL (8.0+)

### ISSUE THREAD

**Issue by lstep** [DiouxX/docker-glpi#18]
When using docker-compose, connecting to GPLI to do the install, cannot connect to MySQL, error giving:
```
The server requested authentication method unknown to the client
```

The current default version is 8.0, but if I modify the `docker-compose.yml`file to set a specific version, like:
```
image: mysql:5.7
```

It works fine.

**Comment by DiouxX** [comment]
If you want to use mysql:8.0, you must add the following line in `/etc/mysql/my.cnf` :

```bash
#Add to phpmyadmin authentication
default_authentication_plugin=mysql_native_password
```
 And restart docker containers.

it's not perfect but it's functional...

**Comment by DiouxX** [comment]
I've specified Mysql version to 5.7.23 in docker-compose file to avoid error connection with latest Mysql version 8+

https://github.com/DiouxX/docker-glpi/commit/c1560a413796e80ce71ac7eb85e30d5e2b446036
