### ISSUE TITLE
启动后，无法更新glpi导致无法使用

### ISSUE THREAD

**Issue by qingfengfenga** [DiouxX/docker-glpi#23]
启动后会容器更新glpi，由于网络限制导致无法下载最新glpi，希望有离线版本使用

**Comment by DiouxX** [comment]
Thanks to use English or French ;-)

**Comment by qingfengfenga** [comment]
Thank you very much for answering my question. After starting the container, glpi-start.sh will connect to the server to download the latest version of GLPI. Some areas can not download the latest GLPI due to network constraints. Hope to use the offline version. Thank you!

**Comment by DiouxX** [comment]
If i understood your case, you will need to download a GLPI version manually : https://github.com/glpi-project/glpi/releases and transfer on your server who need run GLPI.

Extract yourself GLPI tar into your target directory and set a volume with this directory at your glpi container.
Glpi-start.sh would check if directory is empty. If it's not empty, as in present case, it will not try to download GLPI tar.
```
glpi-tmp | basename: missing operand
glpi-tmp | Try 'basename --help' for more information.
glpi-tmp | TLS_REQCERT isn't present
**glpi-tmp | GLPI is already installed**
glpi-tmp | Starting periodic command scheduler: cron.
glpi-tmp | Enabling module rewrite.
glpi-tmp | To activate the new configuration, you need to run:
glpi-tmp |   service apache2 restart
glpi-tmp | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
glpi-tmp | Restarting Apache httpd web server: apache2.
glpi-tmp | Stopping Apache httpd web server: apache2.
glpi-tmp | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
```

That is only functional if your connexion can contact Docker repository or you will have to build manually and locally Docker GLPI image

**Comment by qingfengfenga** [comment]
Thank you very much for your answer. I will try, if everything is normal. I hope more people can see this problem, because like me, there are many people whose network is restricted. Hope to help them!
