### ISSUE TITLE
CAS extension is not present

### ISSUE THREAD

**Issue by jackadam1981** [DiouxX/docker-glpi#24]
CAS extension test | CAS extension is not present

When i use install.php  install glpi, the extension CAS is not present.

**Comment by jackadam1981** [comment]
USE glpi-9.4.4

**Comment by DiouxX** [comment]
Hi,

CAS extension is installed.
Extract from Dockerfile :

`php-cas `

And when i check with fresh install, the CAS extension test is verified.

How do you know the extension is not installed ?
