### ISSUE TITLE
Image Version 9.4.6

### ISSUE THREAD

**Issue by omontigny** [DiouxX/docker-glpi#27]
Good Morning Diouxx

I noticed today that the latest Glpi image you provide has the version number  9.4.6 whereas the latest stable GLPI Official version is 9.4.5 is it normal ? 

So I don't know if it is related but I deployed FusionInventory plugin and when I want to execute the **tasksheduler** task (in automated tasks) , I have a blank page and this error : 

> Fatal error: Cannot redeclare plugin_fusioninventory_footer() (previously declared in /var/www/html/glpi/plugins/fusioninventory/setup.php:596) in /var/www/html/glpi/plugins/Fusioninventory/setup.php on line 596

I already deleted (remove fusionInventory folder) and re-install the fusionInventory plugin but nothing changed. 

For information I am on Mac OS Catalina . I used your exact docker-compose.yml file without volumes for time 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 

Do you have any idea where does it come from please ?
Thank you in advance. 

Best regards

**Comment by DiouxX** [comment]
Hi,

For Glpi Version, the latest version is 9.4.6 as on their [realease page](https://github.com/glpi-project/glpi/releases) 

For Taskscheduler from fusioninventory plugins, i've testing this morning on a fresh install and i've not your error type.

My install version :
* OS : Debian 10 (But i don't think it's important for this issue)
* Glpi : 9.4.6
* FusionInventory plugins : 9.4+2.4

What versions are you using ?

How did you install fusioninventory plugin ?

Can you test with same version that me and give a feedback ?

Best Regards.

**Comment by omontigny** [comment]
Hi DiouxX

Thank you very much for your quick answer. 
I am sorry I don't have Debian server. I have an ubuntu 20.04 desktop I will test on it. 
For the moment I have this config : 

My Install version  : 
  * Mac OS Catalina 10.15.3
  * Your Docker Image GLPI (9.4.6) with your docker-compose file
  * FusionInventory plugins : 9.4+2.4
  * browsers : I test with safari,firefox and chrome

To install the plugin : 
*  I put the tar.gz file in my www/html/glpi/plugins/ volume folder
* then, inside the container I change the ownership : chown -R www-data fusioninventory/
* then in glpi interface I install the plugin and then activate it.

 I confirme the 'execute' button is working when the plugin is deactivated. So the problem comes from the plugin. 



<img width="1598" alt="Capture d’écran 2020-05-14 à 09 27 50" src="https://user-images.githubusercontent.com/17742618/81906008-d9006880-95c5-11ea-8de9-071f8389cf2b.png">
<img width="448" alt="Capture d’écran 2020-05-14 à 09 27 39" src="https://user-images.githubusercontent.com/17742618/81906030-e1f13a00-95c5-11ea-94de-f8aebe2060b2.png">

**Comment by DiouxX** [comment]
The only difference, execpt OS version, is that to change the rights.
I do it from the host system because there's a volume so there's no need to be inside the container.

```bash
diouxx@laptop:~$ sudo chown -R www-data:www-data /var/www/html/glpi/plugins/fusioninventory
```

See if that solves the problem and try on your Ubuntu 20.04.

If it doesn't solve it, it's because the problem is probably at the plugin level and, unfortunately, i can't help for that.

**Comment by omontigny** [comment]
Hi DiouxX

I don't have this www-data:www-data user and group on my local host. 
But it is Exactly a problem with my volume rights because  without the volume the action is working ....
Il really don't understand why . 
I know that MacOs recently  add new restrictions in Catalina with Filesystem rights ... I continue digging ....

**Comment by DiouxX** [comment]
I'm glad we found a solution.

Even though the rights issue on the Mac is still there.
I haven't a Mac so i can't help you with that either.

But if you figure it out, you can give me a feedback. It will be for my general knowledge ;)

**Comment by omontigny** [comment]
It worked also with named volume (which is inside Docker System - so don't really know exactly where it is) . I think It's really un problem with the path I used for my local volume. 
anyway I solved with named-volume but I had to do a 

`docker cp fusioninventory-9.4+2.4.tar.bz2 <CONTAINER_ID>:/var/www/html/glpi/plugins/`
and go inside the container to untar the plugin and change the ownership
`docker exec -ti <CONTAINER_ID> /bin/bash`

` #GLPI Container
  glpi:
    image: diouxx/glpi:latest
    container_name : glpi
    hostname: glpi
    ports:
      - "8282:80"
    volumes:
      - glpi:/var/www/html/glpi
    environment:
      - TIMEZONE=${TZ}
    restart: always

volumes:
  glpi:
`
