### ISSUE TITLE
Request for GLPI docker image 9.5.1

### ISSUE THREAD

**Issue by mecmav** [DiouxX/docker-glpi#31]
Hi,

When the version 9.5.1 will be releases for download?

Thx.

**Comment by DiouxX** [comment]
Hi,

The 9.5.1 glpi version is already available.
When you run the container GLPI, by default, it downloading the latest version.

Except if you specified version with env variable VERSION_GLPI=X.X.X

**Comment by mecmav** [comment]
I cannot update.

I did removed my old image 9.5.0 and downloaded again using docker pull diouxx/glpi:latest, but when I enter in GLPI still yet in 9.5.0

Am I doing something wrong?

**Comment by DiouxX** [comment]
You didn't do anything wrong.

My GLPI image don't support update if there is data in your volume.

```bash
#Extract to glpi-start.sh

if [ "$(ls ${FOLDER_WEB}${FOLDER_GLPI})" ];
then
	echo "GLPI is already installed"
else
	wget -P ${FOLDER_WEB} ${SRC_GLPI}
	tar -xzf ${FOLDER_WEB}${TAR_GLPI} -C ${FOLDER_WEB}
	rm -Rf ${FOLDER_WEB}${TAR_GLPI}
	chown -R www-data:www-data ${FOLDER_WEB}${FOLDER_GLPI}
fi
```

Unfortunately, if you want update GLPI, you must download [tarball release](https://github.com/glpi-project/glpi/releases), extract in your GLPI volume and execute update manually by the web interface.

**Comment by mecmav** [comment]
Understood.

Thanks by your useful reply!

Your project are awesome!

**Comment by DiouxX** [comment]
I would have to add this update feature.

If GLPI version installed is older than latest or spécifiés version so download tarball and extract in the volume 

But I have to find the time to do that...

**Comment by mecmav** [comment]
OK, no problem with it. I will try too, when I have remain a little bit time.

I really aprecciate your help.

**Comment by MaitreDede** [comment]
Hi,
I tried to update to lastet version (9.5.1), by following the documented upgrade process. The upgrade assistant shows missing php extensions : `intl` (required), `zip` (optional), `bz2` (optional).

**Comment by DiouxX** [comment]
Hi,

For this problem, you could try by updating your local image by ```docker pull diouxx/glpi``` and it should be fine.
