### ISSUE TITLE
[SMTP not working] postfix install in dockerfile ?

### ISSUE THREAD

**Issue by fle108** [DiouxX/docker-glpi#33]
i've tried it on kubernetes and everything is ok but i can't send mails from notifications panel. the only way i found to do that is to install manually postfix and configure it in order to be able to send notifications. is there another way or i'm right with postfix ?

**Comment by t3cneo** [comment]
I can send notifications using this image...

What's your ISP/hosting provider?
I discovered with another project some hosting providers block smtp ports (25,465 and 587)
For innstance Scaleway does block outgoing smtp ports by default...

**Comment by fle108** [comment]
hi, i use office365 smtp. 
i didn't found any log in order to help me troubleshoot so i modified the `dockerfile` to add postfix and its config files and it works for `php` but not `smtp`...
maybe a misconfiguration due to old config still there after migration ? (i migrated from bare metal installation in v9.2.1 to 9.5.3 through 3 upgrade steps.
