### ISSUE TITLE
Does not work on ARM

### ISSUE THREAD

**Issue by gado070707** [DiouxX/docker-glpi#34]
Hello,
Is a version planned for raspberry pi?
Thank you in advance.

**Comment by DiouxX** [comment]
Hello,

Currently, there is no arm version planned.
If any contributor can make it, that would be nice.

**Comment by karawitan** [comment]
Hi @gado070707 ,
I have prepared a preliminary Dockerfile as long as a docker-compose.yml file.
Everything is ready to work with a single "make" command (please checkout out the Makefile for details, and docker-compose.yml file to set password as required)

You may test docker-glpi on rpi with:

```
apt-get install make python3
sudo pip install docker-compose
git clone https://github.com/karawitan/docker-glpi.git --branch arm-support
cd docker-glpi
make
```

**Comment by gado070707** [comment]
Hi karawitan,
I have tried now and it works.
Perfect.
A big thank-you 👍
