### ISSUE TITLE
External database

### ISSUE THREAD

**Issue by ValentinPifu** [DiouxX/docker-glpi#36]
We can use an external database? 

We already have GLPI installed (not in docker) but we want to migrate to docker and use the same database.

**Comment by DiouxX** [comment]
You can deploy only Glpi container without databse container.

Either you make a new installation and you inform your remote database server.

![2021-07-28_20h41_51](https://user-images.githubusercontent.com/11738556/127379128-3468a3a0-c898-4ecc-8034-541774b22dc6.png)

![2021-07-28_20h42_18](https://user-images.githubusercontent.com/11738556/127379171-4fe3321f-e4e5-46fe-b8b7-b72d011b1962.png)

Or you deploy only the GLPI container and you copy the data of your existing installation in the volume.
In this way, you should keep the information of your remote database.

**Comment by ValentinPifu** [comment]
I'm connected to the database (a dump from the original one) but I can't see any computers or anything.
I need to do something more?

And if i want to use fusioninvetory plugin, it'll work?

Thank you.

**Comment by DiouxX** [comment]
I would have copied all the data (folder and files) from your old installation to the Docker installation.
Then I would have adapted the _config/config_db.php_ file to connect to your correct database.

Of course you want to use the fsiononventory plugin. I use it in my Docker installation.
You just have to follow the installation instructions:

1. Download the plugin
2. Copy it in the plugins folder
3. Activate it via the web interface in the menu Configurations -> Plugins

**Comment by ValentinPifu** [comment]
Thank you for your response.
I have only one problem with the fussioninventory.
How can I enable the GLPI cron for the fussioninventory plugin?

![Screenshot from 2021-08-05 17-41-58](https://user-images.githubusercontent.com/18114871/128369483-3dac6930-d568-48d5-8b92-731c0bc2245b.png)

**Comment by DiouxX** [comment]
Can you check this issue https://github.com/DiouxX/docker-glpi/issues/6#issuecomment-380374086 ?
The problem was the same and it resolved.

- Changed default execution mode on Auto actions in GLPI to CLI
- Checked log file _glpi/files/log/cron.log_ : ```tail -f glpi/files/_log/cron.log```

**Comment by ValentinPifu** [comment]
Do you mean to change GLPI to CLI for the taskcheduler for fusioninventory? But the notification will stay there or need to disappear?

Nevermind. I just changed to CLI to GLPI => save. changed again from GLPI to CLI => save, error it's gone.
I'll check tomorrow for crons on logs.

![Screenshot from 2021-08-05 21-58-43](https://user-images.githubusercontent.com/18114871/128406069-cfdd82f0-f3c1-44bf-a701-0f2a81820e4c.png)

**Comment by DiouxX** [comment]
Is that your issue is resolved with changed the run mode from GLPI to CLI ?

**Comment by ValentinPifu** [comment]
It was already on CLI and get the information for the cron.
I just change to GLPI , saved, changed again in CLI and saved, now it's working.

You can close the ticket.
Thank you for the support.
