### ISSUE TITLE
Host '172.22.0.2' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by QBANIN** [DiouxX/docker-glpi#38]
GLPI deployed with docker- compose. When i try to set mysql server I get this error 

![image](https://user-images.githubusercontent.com/487657/128246202-bd93855a-ec45-43dd-9bc4-0b89d9762d47.png)

What am I doing wrong?

**Comment by DiouxX** [comment]
What is your docker-compose file ?
The mysql server is also on docker ?

If yes, the mysql server deployed with docker on the same docker-compose or a different docker deployment ?

**Comment by QBANIN** [comment]
**mysql.env**

MYSQL_ROOT_PASSWORD=diouxx
MYSQL_DATABASE=glpidb
MYSQL_USER=glpi_user
MYSQL_PASSWORD=glpi

**docker-compose.yml**

version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
    restart: always


Just deployed the example from installation manual without any changes.

**Comment by DiouxX** [comment]
I have tested now and I don't have the databse initialization problem.

![2021-08-05_16h54_43](https://user-images.githubusercontent.com/11738556/128372516-a78d2ee8-9553-4ed8-98ed-3b66d8ac9a4f.png)

![2021-08-05_16h55_03](https://user-images.githubusercontent.com/11738556/128372548-7c71c07a-ac47-4f60-a90b-793809793f71.png)

![2021-08-05_16h55_14](https://user-images.githubusercontent.com/11738556/128372580-59470fa9-fe26-4c8b-8517-f305209445bd.png)


Are you sure that the _/var/lib/mysql_ folder is empty ?
Is there not data from a previous install ?

Have you tested with another database mapping folder ?

**Comment by DiouxX** [comment]
I'm glad I could help you :)
