### ISSUE TITLE
Plugin installation procedure?

### ISSUE THREAD

**Issue by gustavoberman** [DiouxX/docker-glpi#42]
Hello there!
What should be the procedure to install and configure a plugin using this container?
Thanks

**Comment by DiouxX** [comment]
To update an existing installation, you can use the "traditional" method :

1. Download the archive to your glpi volume.
2. Extract it
3. Copy the contents to the glpi folder
4. Change the access rights to the www-data user with the chown command.
5. Go to the web interface and update
