### ISSUE TITLE
After update the GLPI won't start

### ISSUE THREAD

**Issue by vp-lab** [DiouxX/docker-glpi#45]
I just try to update our GLPI with the newest instance but it'll don't power up.
I get this error:
```
/opt/glpi-start.sh: line 9: /etc/php/7.3/apache2/conf.d/timezone.ini: No such file or directory
/opt/glpi-start.sh: line 10: /etc/php/7.3/cli/conf.d/timezone.ini: No such file or directory
grep: /etc/ldap/ldap.conf: No such file or directory
TLS_REQCERT isn't present
/opt/glpi-start.sh: line 22: /etc/ldap/ldap.conf: No such file or directory
GLPI is already installed
Starting periodic command scheduler: cron.
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Restarting Apache httpd web server: apache2.
Stopping Apache httpd web server: apache2.
```

**Comment by DiouxX** [comment]
After the upgrade to Debian 11, I forgot to adapt the path to the PHP version.
Indeed, with Debian 11 it is php7.4 which is installed and not php 7.3

I also have the bug fix of ldap concerning the file _/etc/ldap/ldap.conf_ which does not exist.

Normally you can start correctly your container after updating the docker image

Sorry for the inconvenience

**Comment by vp-lab** [comment]
It's working now.
Thank you.
