### ISSUE TITLE
GLPI 10.0.0-rc1 - rebuild docker image

### ISSUE THREAD

**Issue by rbrannath** [DiouxX/docker-glpi#50]
Hi there,

could you rebuild the docker image, so the latest glpi 10.0.0-rc1 is avaiable?

I have set environment variable as follows:
`- VERSION_GLPI=10.0.0-rc1`
,but GLPI is still on 10.0.0-dev in my instance.

Thank you very much

**Comment by DiouxX** [comment]
Hi,

If you have an existing glpi installation, changing the GLPI version in the docker-compose will not update glpi.
This functionality is not supported/implemented in the docker image.

To update glpi, you can do it "manually" and "traditionally".

1. Download the tarball
2. Extract it
3. Copy the new content in the installation folder of your glpi
4. Change the rights and the owner if necessary
5. Go to your GLPI web page to proceed with the update.

**Comment by rbrannath** [comment]
I do not have an existing installtion, since I just want to test the new release candidate.
I just did a fork of this repo and build a private docker image myself, which worked.
But thanks for pointing out the regular way, which is the better approach. I will try this next time.
