### ISSUE TITLE
Error during the Pull / Linux / Debian

### ISSUE THREAD

**Issue by jmgway** [DiouxX/docker-glpi#56]
1st - I do the pull
But .... it fails

admin@xsmlsaco17:/var$ **docker pull diouxx/glpi**

_Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/images/create?fromImage=diouxx%2Fglpi&tag=latest: dial unix /var/run/docker.sock: connect: permission denied_

any idea ?

**Comment by DiouxX** [comment]
This is not related to the docker image.
Apparently it's a rights issue on your system

Please read the [docker installation documentation](https://docs.docker.com/engine/install/debian/) and check if you can run the hello-world example.
