### ISSUE TITLE
I can't unzip files on container

### ISSUE THREAD

**Issue by jhonatas-mendes** [DiouxX/docker-glpi#57]
Hi guys, I can't unzip the file "fusioninventory-9.5+3.0.tar.bz2" in the directory /var/www/html/glpi/plugins/ with the tar command nor with the zip command, what can we do to overcome this problem? Grateful

![image](https://user-images.githubusercontent.com/50506812/157583405-176a9e84-13a0-4c1a-8ef4-71a374476bc8.png)

**Comment by DiouxX** [comment]
Hello, 
this is normal because the bzip2 package is not installed.

You can install the package directly in the container :

```bash
apt update && apt install -y bzip2
```

Or you define a volume to map the glpi's folder or just the plugins folder between your host and the container.
Then you extract the archive from the host system
