### ISSUE TITLE
 Missed cron service enabled by default

### ISSUE THREAD

**Issue by jjmarin** [DiouxX/docker-glpi#6]
Hi ! I miss that the cron service enabled by default. It is a service required by the pupular fusion inventory plugin.

So I think that the cron service must be enabled by default and add the following line should be added in /etc/crontab :

* * * * * /usr/bin/php /var/www/html/glpi/front/cron.php &>/dev/null

**Comment by DiouxX** [comment]
Hello
I am using GLPI and the fusioninventory plugin for my own use.
I have no problem with the fusioninventory plugin without cron task.

However, [Glpi's documentation](http://wiki.glpi-project.org/doku.php?id=en:config:crontab) indicate cron task to execute automatically scheduled task.

So i will modify image docker to add this features.

**Comment by DiouxX** [comment]
The cron service is enabled by default.
The follow line is added in /etc/crontab :

`*/5 * * * * /usr/bin/php /var/www/html/glpi/front/cron.php &>/dev/null`

Thanks for your contribution :)

**Comment by Lunaden** [comment]
Is it working ? Apparently cron package is not installed and / or is not started at container start.

**Comment by DiouxX** [comment]
The GLPI cron task is added on /etc/cron file

`*/5 * * * * /usr/bin/php /var/www/html/glpi/front/cron.php &>/dev/null`

So this task check every 5 minutes if an action must be executed.

Can you check content of this file : `/var/www/html/glpi/files/_log/cron.log` ?

For my production and test instance, this feature work fine. 
And the GLPI's file cron.log show all task running correctly

**Comment by Lunaden** [comment]
Fresh deploy on test instance. 
Changed default execution mode on Auto actions in GLPI to -> CLI

I ran : 

`tail -f /var/www/html/glpi/files/_log/cron.log`

Nothing log except
- if i ran manually : 

`/usr/bin/php /var/www/html/glpi/front/cron.php`

- if i launch manually an execution on the action in glpi

- if I change default execution mode on Auto actions in GLPI to -> GLPI and I navigate to the website.


To check if cron is started : 
I ran `dpkg -s cron` inside container

```
dpkg-query: package 'cron' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```
```
service cron status
cron: unrecognized service
```
```
whereis cron
cron: /etc/cron.daily /etc/cron /etc/cron.d
```

**Comment by DiouxX** [comment]
I've testing this steps inside existing container:

- Install cron package : `apt install cron`
- Create an task on _/etc/cron.d/glpi_ : `*/2 * * * * www-data /usr/bin/php /var/www/html/glpi/front/cron.php &>/dev/null`
- Changed default execution mode on Auto actions in GLPI to CLI
- Checked log file _glpi/files/_log/cron.log_ : `tail -f glpi/files/_log/cron.log`

It's working for me.

Can you repeat this steps and confirm if it's working ?
If it's ok, i will modifiy and implement this on default docker images in few days

Source : [config crontask CLI](http://glpi-project.org/DOC/FR/glpi/config_crontaskcli.html)

**Comment by Lunaden** [comment]
Thx a lot for your work !

**Comment by DiouxX** [comment]
Your 're welcome

Thanks for your contribution and your interest.

**Comment by rodrigocaugusto** [comment]
How to edit the cron? i have a problema queuednotification and my mail not send every task.

How can i solve?

Nano not work, not install

**Comment by DiouxX** [comment]
For testing, you can enter into your GLPI container with `docker exec -it <GLPI CONTAINER> /bin/bash`
And add your cron with this command : `echo "<YOUR CRON>" >> /etc/cron.d/glpi`

Or you can install nano and edit cron with it

**Comment by DiouxX** [comment]
You can update the package database before trying to install nano

`apt update && apt install -y nano`

For your notification problem, check your notification settings and your SMTP settings.
If you don't receive the test email, the problem is with your SMTP server
