### ISSUE TITLE
Resolving github.com (github.com)... failed: Temporary failure in name resolution. glpi     

### ISSUE THREAD

**Issue by C138** [DiouxX/docker-glpi#7]
Hello
Trying to docker-compose docker/glpi (latest) ;-)
glpi          | --2018-01-12 15:32:43--  https://github.com/glpi-project/glpi/releases/download//glpi-.tgz
glpi          | Resolving github.com (github.com)... failed: Temporary failure in name resolution.
glpi          | wget: unable to resolve host address 'github.com

This is because, "here", our DNS policy is very strict so that google dns are not (necessearly) reachable...
Maybe it would be sufficient to let  dhcp or local dns policy do the job of configuring the DNS resolving mechanism ... (and thus finding github.com)

??

**Comment by DiouxX** [comment]
Hi,

i don't force Google DNS usage.
Maybe it's implemented on default Debian docker image or an automatic mechanism docker.
I don't know...

You could be configuring DNS settings for your container with **_--dns_** parameter docker
[Configure container DNS](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/)
