### ISSUE TITLE
Upgrade tradional install 9.5 to thsi 10 docker

### ISSUE THREAD

**Issue by orrionis** [DiouxX/docker-glpi#75]
hello
i would know i update  my old version 9.5 in classic install to the docker version.

if i can dump my db via phpmyadmin on old install
how i can push on docker version

Thanks

**Comment by DiouxX** [comment]
Hello,

Yes you can migrate your "classic" install to docker version.

I think the following steps should be taken:

- Make a dump of your existing database
- Create a docker-compose with just the database and optionally phpmyadmin.
- You can initiate the database with your previously created dump.
```yaml
volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./yourdump.sql:/docker-entrypoint-initdb.d/yourdump.sql
```
- Start your docker-compose file
- Check that the database has been correctly initialized and that your data is present (CLI or phpmyadmin).
- Down your docker-compose file
- Modify your docker-compose file to add the GLPI section
- For the first deployment, I would specify the version with the same version as your existing installation : <https://github.com/DiouxX/docker-glpi#deploy-a-specific-release>
- Comment or remove the line in Database section to initiate db with your dump
- Start your docker-compose file and enjoy ! If all is fine ;) 

If all goes well, you can delete the environment variable that specified the GLPI version and update it in the "classic" way.

**Comment by orrionis** [comment]
Hi 
thank for your response.
It 's very detailed , i try this , and post after it all goes well

**Comment by orrionis** [comment]
it's work fine thankyou so mutch
