### ISSUE TITLE
Error PHP 7.4

### ISSUE THREAD

**Issue by oselow** [DiouxX/docker-glpi#88]
Since you've update the docker image, I've an error and can't lauch glpi :
<img width="672" alt="Capture d’écran 2023-04-27 à 15 55 31" src="https://user-images.githubusercontent.com/37409980/234885161-eecdfa62-d829-4b61-b87a-047a9cd949ef.png">

**Comment by DiouxX** [comment]
Yes, this is my mistake...
I forgot to update this part of the script.

It's normally fixed now with latest commit https://github.com/DiouxX/docker-glpi/commit/69940f5ec132637a6631e4ecbf221eabb8d30e0f
Can you confirm?

**Comment by oselow** [comment]
So I had fixed it via a volume and passing the patch, there with the new commit, everything seems to be good for this error without needing a volume but now it's 404, I look on my side.

**Comment by oselow** [comment]
I think it's the new virtual host introduce in april

**Comment by oselow** [comment]
solved by the issue #89
