### ISSUE TITLE
unable to keep /glpi/

### ISSUE THREAD

**Issue by ksourdrille** [DiouxX/docker-glpi#93]
Hello,

I am facing a problem concerning the 10.0.7 update, historically my GLPI is available with http://IP/glpi/, in 10.0.3 I was not with docker, for simplicity of management I decided to move to version 10.0.6 with docker and therefore your GLPI container, for version 10.0.6 I modified the launch script to keep the /glpi, I must keep it because my workstation park with the agent fusioninventory is targeted http://ip/glpi/plugins/fusioninventory/. 

However, for the 10.0.7 update and your container, it's impossible for me to get the /glpi instead of the /. I've looked at the documentation and they give an alias, but that doesn't work either.

![image](https://github.com/DiouxX/docker-glpi/assets/100124349/09cbddac-4666-4e14-b5a7-0e907ec0355a)

Do you have any ideas?

Kélian

**Comment by DiouxX** [comment]
Fixed with #91
