### ISSUE TITLE
Glpi crashed after update latest

### ISSUE THREAD

**Issue by tbaror** [DiouxX/docker-glpi#95]
Hello ,
I have Glpi docker running for 9 month , today  i tried to update the docker image ,since then it wont start , i have following blow log file
Don't know how to fix it , even tried to create new docker with same issue. 
Please advice
Thanks
[glpi_logs(1).txt](https://github.com/DiouxX/docker-glpi/files/12088301/glpi_logs.1.txt)

**Comment by DiouxX** [comment]
Sorry for the late reply.

Is the problem still there ?
